#! /bin/python

import socket
import time
import thread
import sys

angle = 0
velocity = 15

HOST = 'localhost'
PORT = 3490
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
#bind the socket to a public host,
# and a well-known port
s.connect((HOST, PORT))

def name():
	s.sendall('n memo  \n')
	send()
	time.sleep( 1 )
	s.sendall('n  memo \n')
	send()
	time.sleep( 1 )
	s.sendall('n   memo\n')
	send()
	time.sleep( 1 )
	s.sendall('n    mem\n')
	send()
	time.sleep( 1 )
	s.sendall('n     me\n')
	send()
	time.sleep( 1 )
	s.sendall('n      m\n')
	send()
	time.sleep( 1 )
	s.sendall('n       \n')
	send()
	time.sleep( 1 )
	s.sendall('n o     \n')
	send()
	time.sleep( 1 )
	s.sendall('n mo    \n')
	send()
	time.sleep( 1 )
	s.sendall('n emo   \n')
	send()
	time.sleep( 1 )

def send():
	s.sendall('v '+str(velocity)+'\n')
	s.sendall(str(angle)+'\n')

def ninput(s):
	while True:
		ninput = raw_input("> ")
		if('v' in ninput):
			global velocity
			velocity = ninput.split().pop()
		elif('c' in ninput):
			s.sendall('c\n')
		elif ninput:
			try:
				global angle
				angle = float(ninput)
			except ValueError:
				print "not a valid angle"
			print angle


if len(sys.argv) > 1 and ('b' in sys.argv[1]):
	s.sendall('n memoBot\n')
	print "sending..."
	if sys.argv[2]:
		angle = float(sys.argv[2])
	while True:
		angle = angle + 1
		s.sendall('v '+str(velocity)+'\n')
		s.sendall(str(angle)+'\n')
		time.sleep(5)
else:
	s.sendall('n memo\n')
	thread.start_new_thread(ninput,(s,))
	while True:
		name()
		send()
s.close()
